ChefSolutions/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import homepage, aboutus, search


urlpatterns = [
    path('', homepage, name="index"),
    path('aboutus', aboutus, name="aboutus"),
    path('search', search, name="search"),
    path('auth/', include('social_django.urls', namespace='social')),
    path('customer/', include('customer.urls')),
    path('admin/', admin.site.urls),
    path('error/', include('Error.urls')),
    path('cart/', include('cart.urls')),
    path('products/', include('products.urls')),
    path('placeorder/', include('order.urls')),
    path('blog/', include('blog.urls')),
    path('payment/', include('payment.urls'), name="payment"),
    path('managecs/', include('manageCS.urls'), name="manageCS"),
    path('coupon/', include('coupon.urls'), name="manageCS"),
]

blog/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import addRecipe, recipes, printRecipe, recipesDetail, addComment

app_name = 'blog'

urlpatterns = [
    path('', recipes, name="recipe"),
    path('<int:id>/', recipesDetail, name="recipesDetail"),
    path('add', addRecipe, name="addrecipe"),
    path('print_recipe/<int:rid>', printRecipe, name="printrecipe"),
    path('addComment', addComment, name="addComment"),
]

cart/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import cart, addInCart, deleteCart, clearCart

app_name = 'cart'

urlpatterns = [
    path('', cart, name="cart"),
    path('add', addInCart, name="addcart"),
    path('delete', deleteCart, name="deletecart"),
    path('clear', clearCart, name="deletecart"),
]

customer/urls.py
from django.contrib import admin
from django.urls import path, re_path
from django.conf.urls import url
from .views import login, signup, profile, logout, forgotPassword, changePassword, accoutVarification
from .views import updatePassword, updateProfile

app_name = 'customer'

urlpatterns = [
    path('login', login, name="login"),
    path('logout', logout, name="logout"),
    path('signup', signup, name="signup"),
    re_path(r'^forgotpassword', forgotPassword, name="forgot"),
    re_path(r'^verify', accoutVarification, name="varify"),
    path('changepassword', changePassword, name="changepassword"),
    path('updatepassword', updatePassword, name="updatepassword"),
    path('updateprofile', updateProfile, name="updateprofile"),
    path('profile', profile, name="profile"),
]

products/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from .views import allProducts, prductDetail

app_name = 'products'

urlpatterns = [
    path('', allProducts, name="all_products"),
    path('details/<int:pid>', prductDetail, name="product_details"),
]

templates/extends/main.html
<!DOCTYPE html>
{% load static%}
<html>

<head>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Herr+Von+Muellerhoff" rel="stylesheet">
    {% comment %}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    {% endcomment %}
    <link rel="stylesheet" href="{% static 'css/materialize.min.css' %}">
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <link rel="stylesheet" href="{% static 'css/navbar.css'%}">
    {% block styles %}

    {% endblock styles %}

    <title>
        {% block title %}

        {% endblock title %}
    </title>
</head>

<body>
    {% include "./navbar.html" %}

    {% block content %}

    {% endblock content %}


    <div class="row section grey darken-4" style="margin-bottom: 0px;">
        <div class="section">
            <form>
                <div class="col s12 m4 offset-m3">
                    <input type="email" style="padding-left: 2px;border: 1px grey solid; background: white;" placeholder="Signup For Newsletter">
                </div>
                <div class="col s12 m2">
                    <button class="btn wave green" type="submit" style="height: 42px; margin-top: 1px;">Subscribe</button>
                </div>
            </form>
        </div>
    </div>
    <footer class="page-footer grey darken-3" >
        <div class="row" style="margin: 10px;">
            <div class="col s12 m3">
                <h4 class="white-text" style="margin-top: 0;">Chef's Solution</h4>
                <p class="grey-text">Cannot Place, New Delhi</p>
                <p class="grey-text">abc@abc.com</p>
                <p class="grey-text">1234567890</p>
            </div>
            <div class="col s12 m2 offset-m1">
                <h6 class="green-text">Quick Links</h6>
                <ul>
                    <li><a class="grey-text text-lighten-3" href="{% url 'blog:recipe' %}">Blog</a></li>
                    <li><a class="grey-text text-lighten-3" href="{% url 'products:all_products' %}?category=none">Products</a></li>
                </ul>
            </div>

            <div class="col s12 m2">
                <h6 class="green-text">Information</h6>
                <ul>
                    <li><a class="grey-text text-lighten-3" href="#!">Privacy Policy</a></li>
                    <li><a class="grey-text text-lighten-3" href="#!">User Policy</a></li>
                </ul>
            </div>
        </div>
        
        <div class="footer-copyright">
            <div class="container center-align">
                <h6>&copy; Chef's Solution</h6>
            </div>
        </div>
    </footer>

    <script src="{% static 'js/jquery-3.3.1.min.js' %}" ></script>
    <script  src="{% static 'js/materialize.min.js' %}"></script>

    {% block scripts %}

    {% endblock scripts %}

</body>

</html>

templates/extends/navbar.html
<div class="navbar-fixed">
    <nav class="z-depth-0">
        <div class="nav-wrapper">
            <a href="#" data-target="mobile-demo" class="sidenav-trigger"><i class="material-icons">menu</i></a>
            <ul class="left hide-on-med-and-down nav-links">
                <li><a href="{% url 'index' %}">Home</a></li>
                <li><a href="{% url 'aboutus' %}">About Us</a></li>
                <li><a href="{% url 'products:all_products' %}?category={{ 'none' | urlencode }} ">CS Shop</a></li>
                <li><a href="mobile.html">My CS</a></li>
                <li><a href="{% url 'blog:recipe' %}">Recipes</a></li>
                <li><a href="mobile.html">Community</a></li>
                <li><a href="mobile.html">Contact Us</a></li>
            </ul>

            <form style="display: inline-block; width: 200px;" action="/search" method="GET">
                <div class="input-field">
                    <input id="search" type="search" name="item" required>
                    <label class="label-icon" for="search"><i class="material-icons">search</i></label>
                    <i class="material-icons">close</i>
                </div>
            </form>
            
            <ul class="right hide-on-med-and-down nav-links">
                
                <li><a class="material-icons shopping-cart" href="{% url 'cart:cart' %}"><i>add_shopping_cart</i></a></li>
                {% if customer %}
                <li><a href="{% url 'customer:logout'%}">LogOut</a></li>
                <li><a href="{% url 'customer:profile'%}">Profile</a></li>
                {% else %}
                <li><a href="{% url 'customer:login'%}">LogIn</a></li>
                <li><a href="{% url 'customer:signup'%}">SignUp</a></li>
                {% endif %}

            </ul>
        </div>
    </nav>
</div>

<div class="navbar" id="secondNav">
    <nav class="z-depth-1">
        <div class="nav-wrapper">
            <a href="#" class="brand-logo center">The Chef's Solution</a>
        </div>
    </nav>
</div>

<ul class="sidenav" id="mobile-demo">
    <li><a href="sass.html">HOME</a></li>
    <li><a href="badges.html">MENU</a></li>
    <li><a href="collapsible.html">BLOG</a></li>
    <li><a href="mobile.html">SHOP</a></li>
</ul>