ChefSolutions/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import homepage, aboutus, search


urlpatterns = [
    path('', homepage, name="index"),
    path('aboutus', aboutus, name="aboutus"),
    path('search', search, name="search"),
    path('auth/', include('social_django.urls', namespace='social')),
    path('customer/', include('customer.urls')),
    path('admin/', admin.site.urls),
    path('error/', include('Error.urls')),
    path('cart/', include('cart.urls')),
    path('products/', include('products.urls')),
    path('placeorder/', include('order.urls')),
    path('blog/', include('blog.urls')),
    path('payment/', include('payment.urls'), name="payment"),
    path('managecs/', include('manageCS.urls'), name="manageCS"),
    path('coupon/', include('coupon.urls'), name="manageCS"),
]

Error/urls.py
from django.urls import path, re_path
from .views import error

app_name = 'error'

urlpatterns = [
    path('', error, name="error"),
]

blog/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import addRecipe, recipes, printRecipe, recipesDetail, addComment

app_name = 'blog'

urlpatterns = [
    path('', recipes, name="recipe"),
    path('<int:id>/', recipesDetail, name="recipesDetail"),
    path('add', addRecipe, name="addrecipe"),
    path('print_recipe/<int:rid>', printRecipe, name="printrecipe"),
    path('addComment', addComment, name="addComment"),
]

products/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from .views import allProducts, prductDetail

app_name = 'products'

urlpatterns = [
    path('', allProducts, name="all_products"),
    path('details/<int:pid>', prductDetail, name="product_details"),
]

templates/base/aboutus.html
{% extends '../extends/main.html' %}

{% load static %}

{% block styles %}
<link rel="stylesheet" href="{% static 'css/topImage.css' %}">
{% endblock styles %}   

{% block content %}
<div class="top-image">
    <div class="first center-align">
        <span>
            About
        </span>
    </div>
    <div class="second center-align">
        <span>
            Us
        </span>
    </div>
</div>

<div class="container" >
    <p class="flow-text " style=" text-align: justify;text-justify: inter-word;">
        <small>Chef Solutions is a house brand of Namosri Ventures Pvt. Ltd. (NVPL). NVPL is specializing in high quality and innovative food brands serving primarily to Food Service sector. We offer a comprehensive range of ingredients spread across segments of Coating, Breading, Bakery, Seasonings, Marinades, Gravies, Sauces, Broths and Specialty Ingredients for Food Service as well as Food Industry applications. </small>
    </p>
    <p class="flow-text " style=" text-align: justify; text-justify: inter-word;">
        <small>Chef Solutions is chefs’ best friend as it enables chefs to serve delicious, wholesome meals to their guests. The brand creates essential ingredients that save precious preparation time in the kitchen, without compromising on the flavour. Being part of NVPL, Chef Solutions uses the highly-skilled R&D and Chefs’ team to create product compositions that are rich and flavoursome. The ingredients allow chefs to experiment with flavour and add their magic to the dishes. </small>
    </p>
    <p class="flow-text" style=" text-align: justify; text-justify: inter-word;"> 
        <small>We are extremely passionate about great food and this has allowed us to develop state-of-the-art product range. Every day, thousands of Chefs use our products at star hotels, stand-alone restaurants, chain restaurants, QSRs, and catering businesses to please the palette of their discerning customers.</small>
    </p>
</div>

{% endblock content %}

templates/base/error.html
<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>404</title>
	<!-- Google font -->
	<link href="https://fonts.googleapis.com/css?family=Montserrat:500" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css?family=Titillium+Web:700,900" rel="stylesheet">
    <style>
                * {
          -webkit-box-sizing: border-box;
                  box-sizing: border-box;
        }

        body {
          padding: 0;
          margin: 0;
        }

        #notfound {
          position: relative;
          height: 100vh;
        }

        #notfound .notfound {
          position: absolute;
          left: 50%;
          top: 50%;
          -webkit-transform: translate(-50%, -50%);
              -ms-transform: translate(-50%, -50%);
                  transform: translate(-50%, -50%);
        }

        .notfound {
          max-width: 767px;
          width: 100%;
          line-height: 1.4;
          padding: 0px 15px;
        }

        .notfound .notfound-404 {
          position: relative;
          height: 150px;
          line-height: 150px;
          margin-bottom: 25px;
        }

        .notfound .notfound-404 h1 {
          font-family: 'Titillium Web', sans-serif;
          font-size: 186px;
          font-weight: 900;
          margin: 0px;
          text-transform: uppercase;
          {#background: url('../img/text.png');#}
          -webkit-background-clip: text;
          -webkit-text-fill-color: transparent;
          background-size: cover;
          background-position: center;
        }

        .notfound h2 {
          font-family: 'Titillium Web', sans-serif;
          font-size: 26px;
          font-weight: 700;
          margin: 0;
        }

        .notfound p {
          font-family: 'Montserrat', sans-serif;
          font-size: 14px;
          font-weight: 500;
          margin-bottom: 0px;
          text-transform: uppercase;
        }

        .notfound a {
          font-family: 'Titillium Web', sans-serif;
          display: inline-block;
          text-transform: uppercase;
          color: #fff;
          text-decoration: none;
          border: none;
          background: #5c91fe;
          padding: 10px 40px;
          font-size: 14px;
          font-weight: 700;
          border-radius: 1px;
          margin-top: 15px;
          -webkit-transition: 0.2s all;
          transition: 0.2s all;
        }

        .notfound a:hover {
          opacity: 0.8;
        }

        @media only screen and (max-width: 767px) {
          .notfound .notfound-404 {
            height: 110px;
            line-height: 110px;
          }
          .notfound .notfound-404 h1 {
            font-size: 120px;
          }
        }

    </style>
</head>
<body>

	<div id="notfound">
		<div class="notfound">
			<div class="notfound-404">
				<h1>404</h1>
			</div>
			<h2>Oops! This Page Could Not Be Found</h2>
			<p>Sorry but the page you are looking for does not exist, have been removed. name changed or is temporarily unavailable</p>
			<a href="/">Go To Homepage</a>
		</div>
	</div>
</body>

</html>

templates/base/index.html
{% extends "../extends/main.html" %}

{% load static %}

{% block styles %}
<link rel="stylesheet" href="{% static 'css/index.css'%}" />
{% endblock styles %}

{% block title %}
Chef's Solution
{% endblock title %}

{% block content %}
<div class="first">
    <div class="welcome center-align">
        <span>Welcome</span>
    </div>
    <div class="solution center-align">
        <span>THE CHEF'S SOLUTION</span>
    </div>
</div>

<div class="my-card section">
    <div class="row container">
        <div class="col s12 card-panel">
            <div class="row">
                <div class="col s12 m6">
                    <span>Discover</span>
                    <p class="flow-text center-align">
                        Lorem ipsum dolor sit amet consectetur adipisicing elit. Ad nihil porro voluptatem blanditiis
                        et consequatur modi delectus debitis soluta perferendis est sapiente, veniam alias
                        necessitatibus explicabo repudiandae numquam cumque voluptate!
                    </p>
                </div>
                <div class="col s12 m6 bgimage">
                </div>
            </div>
        </div>
    </div>
</div>

<div class="card-panel z-depth-4 row" style="margin: 10px;">
    <h3>Recent Recipes</h3>
    <div class="container">
        {% for recipe in recipes %}
        <div class="col s12 m4">
            
            <a href="/blog/{{ recipe.id }}">
                <div class="card">
                    <div class="card-image">
                        <img src="/{{ recipe.picture_1 }}">
                    </div>
                    <div class="card-content center-align">
                        <p>{{ recipe.name }}</p>
                    </div>
                </div>
            </a>

        </div>
        {% endfor %}
    </div>
</div>

<div class="my-card section">
    <div class="row container">
        <div class="col s12 card-panel">
            <div class="row">
                <div class="col s12 m6">
                    <span>Discover</span>
                    <p class="flow-text center-align">
                        Lorem ipsum dolor sit amet consectetur adipisicing elit. Ad nihil porro voluptatem blanditiis
                        et consequatur modi delectus debitis soluta perferendis est sapiente, veniam alias
                        necessitatibus explicabo repudiandae numquam cumque voluptate!
                    </p>
                </div>
                <div class="col s12 m6 bgimage">
                </div>
            </div>
        </div>
    </div>
</div>

<div class="card-panel z-depth-4 row" style="margin: 10px;">
    <h3>Products</h3>
    <div class="container">
        {% for product in products %}
        <div class="col s12 m4">
            
            <a href="/products/details/{{ product.id }}">
                <div class="card">
                    <div class="card-image">
                        <img src="/{{ product.picture_1 }}">
                    </div>
                    <div class="card-content center-align">
                        <p>{{ product.name }}</p>
                    </div>
                </div>
            </a>

        </div>
        {% endfor %}
    </div>
</div>

{% endblock content %}

{% block scripts %}
<script src="{%static 'js/index.js'%}"></script>
{% endblock scripts %}

templates/base/search.html
{% extends "../extends/main.html" %}
{% load static %}

{% block styles %}
<link rel="stylesheet" href="{% static 'css/topImage.css' %}">
{% endblock styles %}

{% block content %}

<div class="container">
    <h3>Products</h3>
    {% if product %}

        {% if product.productName %}
        <h5>Products With Name Matches</h5>
        {% for pro in product.productName %}
        <div class="card blue-grey darken-1">
            <a href="{% url 'products:product_details' pid=pro.id %}">
                <div class="card-content white-text">
                    <span class="card-title">{{ pro.name }}</span>
                    <p>Name = {{ pro.name }}</p>
                </div>
            </a>
        </div>
        {% endfor %}
        {% else %}
        {% endif %}

        {% if product.productDescription %}
        <h5>Products With Description Matches</h5>
        {% for pro in product.productDescription %}
        <div class="card blue-grey darken-1">
            <a href="{% url 'products:product_details' pid=pro.id %}">
                <div class="card-content white-text">
                    <span class="card-title">{{ pro.name }}</span>
                    <p>Description = {{ pro.description }}</p>
                </div>
            </a>
        </div>
        {% endfor %}
        {% else %}
        {% endif %}

        {% if product.productUses %}
        <h5>Products With Use of Product Matches</h5>
        {% for pro in product.productUses %}
        <div class="card blue-grey darken-1">
            <a href="{% url 'products:product_details' pid=pro.id %}">
                <div class="card-content white-text">
                    <span class="card-title">{{ pro.name }}</span>
                    <p>Product Uses = {{ pro.uses }}</p>
                </div>
            </a>
        </div>
        {% endfor %}
        {% else %}
        {% endif %}

        {% if product.productBenefits %}
        <h5>Products With Benefits of Product Matches</h5>
        {% for pro in product.productBenefits %}
        <div class="card blue-grey darken-1">
            <a href="{% url 'products:product_details' pid=pro.id %}">
                <div class="card-content white-text">
                    <span class="card-title">{{ pro.name }}</span>
                    <p>Product Benefits = {{ pro.benefits }}</p>
                </div>
            </a>
        </div>
        {% endfor %}
        {% else %}
        {% endif %}

        {% if product.productIngridients %}
        <h5>Products With Ingridients Matches</h5>
        {% for pro in product.productIngridients %}
        <div class="card blue-grey darken-1">
            <a href="{% url 'products:product_details' pid=pro.id %}">
                <div class="card-content white-text">
                    <span class="card-title">{{ pro.name }}</span>
                    <p>Product Ingridients = {{ pro.ingridients }}</p>
                </div>
            </a>
        </div>
        {% endfor %}
        {% else %}
        {% endif %}

        {% if product.productDirection %}
        <h5>Products With Directions of Use Matches</h5>
        {% for pro in product.productDirection %}
        <div class="card blue-grey darken-1">
            <a href="{% url 'products:product_details' pid=pro.id %}">
                <div class="card-content white-text">
                    <span class="card-title">{{ pro.name }}</span>
                    <p>Direction of Use = {{ pro.directions }}</p>
                </div>
            </a>
        </div>
        {% endfor %}
        {% else %}
        {% endif %}

    {% else %}
        <p class="flow-text">No Product Found</p>
    {% endif %}

    <h3>Recipes</h3>
    {% if recipe %}

        {% if recipe.recipeName %}
        <h5>Recipes With Name Matches</h5>
        {% for rec in recipe.recipeName %}
        <div class="card blue-grey darken-1">
            <a href="{% url 'blog:recipesDetail' id=rec.id %}">
                <div class="card-content white-text">
                    <span class="card-title">{{ rec.name }}</span>
                    <p>Name = {{ rec.name }}</p>
                </div>
            </a>
        </div>
        {% endfor %}
        {% else %}
        {% endif %}

        {% if recipe.recipeIngredients %}
        <h5>Recipes With Ingredients Matches</h5>
        {% for rec in recipe.recipeIngredients %}
        <div class="card blue-grey darken-1">
            <a href="{% url 'blog:recipesDetail' id=rec.id %}">
                <div class="card-content white-text">
                    <span class="card-title">{{ rec.name }}</span>
                    <p>Ingredients = {{ rec.ingredients }}</p>
                </div>
            </a>
        </div>
        {% endfor %}
        {% else %}
        {% endif %}

        {% if recipe.recipeFoodGroup %}
        <h5>Recipes With Food Groupt Matches</h5>
        {% for rec in recipe.recipeFoodGroup %}
        <div class="card blue-grey darken-1">
            <a href="{% url 'blog:recipesDetail' id=rec.id %}">
                <div class="card-content white-text">
                    <span class="card-title">{{ rec.name }}</span>
                    <p>Food Group = {{ rec.food_group }}</p>
                </div>
            </a>
        </div>
        {% endfor %}
        {% else %}
        {% endif %}

        {% if recipe.recipeCookingProcessName %}
        <h5>Recipes With Cooking Process Name Matches</h5>
        {% for rec in recipe.recipeCookingProcessName %}
        <div class="card blue-grey darken-1">
            <a href="{% url 'blog:recipesDetail' id=rec.id %}">
                <div class="card-content white-text">
                    <span class="card-title">{{ rec.name }}</span>
                    <p>Cooking Process Name = {{ rec.cooking_process_name }}</p>
                </div>
            </a>
        </div>
        {% endfor %}
        {% else %}
        {% endif %}

        {% if recipe.recipeCookingProcessMethod %}
        <h5>Recipes With Cooking Process Method Matches</h5>
        {% for rec in recipe.recipeCookingProcessMethod %}
        <div class="card blue-grey darken-1">
            <a href="{% url 'blog:recipesDetail' id=rec.id %}">
                <div class="card-content white-text">
                    <span class="card-title">{{ rec.name }}</span>
                    <p>Cooking Process Method = {{ rec.cooking_process_method }}</p>
                </div>
            </a>
        </div>
        {% endfor %}
        {% else %}
        {% endif %}

    {% else %}
        <p class="flow-text">No Recipes Found</p>
    {% endif %}

</div>

{% endblock content %}