ChefSolutions/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import homepage, aboutus, search


urlpatterns = [
    path('', homepage, name="index"),
    path('aboutus', aboutus, name="aboutus"),
    path('search', search, name="search"),
    path('auth/', include('social_django.urls', namespace='social')),
    path('customer/', include('customer.urls')),
    path('admin/', admin.site.urls),
    path('error/', include('Error.urls')),
    path('cart/', include('cart.urls')),
    path('products/', include('products.urls')),
    path('placeorder/', include('order.urls')),
    path('blog/', include('blog.urls')),
    path('payment/', include('payment.urls'), name="payment"),
    path('managecs/', include('manageCS.urls'), name="manageCS"),
    path('coupon/', include('coupon.urls'), name="manageCS"),
]

blog/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import addRecipe, recipes, printRecipe, recipesDetail, addComment

app_name = 'blog'

urlpatterns = [
    path('', recipes, name="recipe"),
    path('<int:id>/', recipesDetail, name="recipesDetail"),
    path('add', addRecipe, name="addrecipe"),
    path('print_recipe/<int:rid>', printRecipe, name="printrecipe"),
    path('addComment', addComment, name="addComment"),
]

cart/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import cart, addInCart, deleteCart, clearCart

app_name = 'cart'

urlpatterns = [
    path('', cart, name="cart"),
    path('add', addInCart, name="addcart"),
    path('delete', deleteCart, name="deletecart"),
    path('clear', clearCart, name="deletecart"),
]

customer/urls.py
from django.contrib import admin
from django.urls import path, re_path
from django.conf.urls import url
from .views import login, signup, profile, logout, forgotPassword, changePassword, accoutVarification
from .views import updatePassword, updateProfile

app_name = 'customer'

urlpatterns = [
    path('login', login, name="login"),
    path('logout', logout, name="logout"),
    path('signup', signup, name="signup"),
    re_path(r'^forgotpassword', forgotPassword, name="forgot"),
    re_path(r'^verify', accoutVarification, name="varify"),
    path('changepassword', changePassword, name="changepassword"),
    path('updatepassword', updatePassword, name="updatepassword"),
    path('updateprofile', updateProfile, name="updateprofile"),
    path('profile', profile, name="profile"),
]

customer/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.


class Customers(models.Model):
    id = models.IntegerField(primary_key=True)
    name = models.CharField(max_length=200)
    email = models.CharField(max_length=200, unique=True)
    password = models.CharField(max_length=500)
    mobile = models.CharField(max_length=10)
    temp_id = models.CharField(max_length=500, default='0')
    dob = models.DateField(default=None, null=True)
    is_active = models.BooleanField(default=False)
    is_b2b = models.BooleanField(default=False)
    is_admin = models.BooleanField(default=False)
    profile_pic = models.FileField(
        upload_to='static/customer/profile', default="static/customer/profile/default.png")

    class Meta:
        db_table = "customer"


class Address(models.Model):
    id = models.IntegerField(primary_key=True)
    customer_id = models.ForeignKey(Customers, on_delete=models.CASCADE)
    street = models.CharField(max_length=500)
    city = models.CharField(max_length=500)
    state = models.CharField(max_length=500)
    country = models.CharField(max_length=500)
    pincode = models.IntegerField()

    class Meta:
        db_table = "address"



class RequestForB2B(models.Model):
    id = models.IntegerField(primary_key=True)
    customer_id = models.ForeignKey(Customers, on_delete=models.CASCADE)
    is_responsed = models.BooleanField(default=False)

    class Meta:
        db_table = "request_for_b2b"

customer/forms.py
from django import forms

class loginForm(forms.Form):
    email = forms.EmailField(label="email", max_length=100)
    password = forms.CharField(label="password", max_length=100)


class signUpForm(forms.Form):
    name = forms.CharField(label="name", max_length=100)
    email = forms.EmailField(label="email", max_length=100)
    mobile = forms.CharField(label="mobile", max_length=10)
    password = forms.CharField(label="password", max_length=100)

customer/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.contrib.auth.hashers import make_password, check_password
from django.utils.crypto import get_random_string
from django.core.mail import EmailMessage

from .forms import loginForm, signUpForm
from .models import Customers, Address
from cart.models import Cart
from order.models import Orders
import getResponses

data = {
    "title": "Chef Solutions",
    "message": ""
}

def login(request):
    data = getResponses.getResponse(request)
    data['message'] = ""
    if 'customer_id' not in request.session:
        if request.method == 'POST':
            loginform = loginForm(request.POST)
            if loginform.is_valid():
                email = loginform.cleaned_data['email']
                password = loginform.cleaned_data['password']
                customer = Customers.objects.filter(email=email)
                if customer:
                    if check_password(password, customer[0].password):
                        if customer[0].is_active:
                            request.session['customer_id'] = customer[0].id
                            print(customer[0].id)
                            if 'temp_customer_id' in request.session:
                                cart = Cart.objects.filter(
                                    temp_customer_id=request.session['temp_customer_id'])
                                cart.update(
                                    temp_customer_id='0', customer_id=request.session['customer_id'])
                                del request.session['temp_customer_id']
                            return redirect('customer:profile')
                        else:
                            data['message'] = "Your account is not activated yet"
                            return render(request, "customer/login.html", data)
                    else:
                        data['message'] = "Password Incorrect"
                        return render(request, "customer/login.html", data)
                else:
                    data['message'] = "User not exists"
                    return render(request, "customer/login.html", data)
            else:
                data['message'] = "Invalid Form"
                return render(request, "customer/login.html", data)
        else:
            if 'customer_id' in request.session:
                return redirect('customer:profile')
            else:
                return render(request, "customer/login.html", data)
    else:
        return redirect("customer:profile")


def signup(request):
    data = getResponses.getResponse(request)
    data['message'] = ""
    if 'customer_id' not in request.session:
        if request.method == 'POST':
            signupform = signUpForm(request.POST)
            if signupform.is_valid():
                email = signupform.cleaned_data['email']
                password = signupform.cleaned_data['password']
                name = signupform.cleaned_data['name']
                mobile = signupform.cleaned_data['mobile']
                if Customers.objects.filter(email=email):
                    data['message'] = "Email alreay Exists"
                    return render(request, "customer/signup.html", data)
                else:
                    customer = Customers()
                    customer.name = name
                    customer.email = email
                    customer.password = make_password(password)
                    customer.mobile = mobile
                    customer.temp_id = get_random_string(length=200)
                    customer.save()

                    body = "Please click on below link for Account verification\n "
                    body += "http://localhost:8000/customer/verify?id=" + customer.temp_id
                    email = EmailMessage('Chef Solutions', body, to=[email])
                    email.send()
                    data['message'] = "check your email for account varification"
                    return render(request, "customer/signup.html", data)
            else:
                return redirect('error:error')
        else:
            return render(request, "customer/signup.html", data)
    else:
        return redirect("error:error")


def profile(request):
    data = getResponses.getResponse(request)
    data['message'] = ""
    if 'customer_id' in request.session:
        customer = Customers.objects.filter(id=request.session['customer_id'])
        data["name"] = customer[0].name
        data["email"] = customer[0].email
        data["mobile"] = customer[0].mobile
        data["image"] = customer[0].profile_pic
        address = Address.objects.filter(
            customer_id=Customers.objects.filter(id=request.session['customer_id'])[0])
        data["address"] = address
        my_orders = Orders.objects.filter(customer_id=customer[0])
        print(my_orders)
        # my_orders = Orders.objects.all()
        # print(my_orders)
        data["orders"] = my_orders
        return render(request, "customer/profile.html", data)
    else:
        return redirect('customer:login')


def logout(request):
    data = getResponses.getResponse(request)
    data['message'] = ""
    if 'customer_id' in request.session:
        del request.session['customer_id']
        return redirect('index')
    else:
        return redirect('customer:login')


def forgotPassword(request):
    data = getResponses.getResponse(request)
    data['message'] = ""
    if request.method == "POST":
        email = request.POST["email"]
        customer = Customers.objects.filter(email=email)
        if customer:
            temp_id = get_random_string(length=200)
            customer.update(temp_id=temp_id)
            body = "Please click on below link for password change\n "
            body += "http://localhost:8000/customer/forgotpassword?id="+temp_id
            email = EmailMessage('Chef Solutions', body, to=[email])
            email.send()
            data['message'] = "Email sent to Your email"
            return render(request, "customer/forgotpassword.html", data)
        else:
            data['message'] = "No Such Customer"
            return render(request, "customer/forgotpassword.html", data)
    else:
        if 'id' in request.GET:
            id = request.GET['id']
            if id != '0':
                customer = Customers.objects.filter(temp_id=id)
                if customer:
                    data['temp_id'] = id
                    return render(request, "customer/changepassword.html", data)
                else:
                    data['message'] = "wrong request"
                    return render(request, "customer/forgotpassword.html", data)
            else:
                data['message'] = "wrong request"
                return render(request, "customer/forgotpassword.html", data)
        else:
            return render(request, "customer/forgotpassword.html", data)


def changePassword(request):  # for forgot password
    data = getResponses.getResponse(request)
    data['message'] = ""
    if request.method == "POST":
        temp_id = request.POST['temp_id']
        password = request.POST['password']
        if temp_id != '0':
            customer = Customers.objects.filter(temp_id=temp_id)
            if customer:
                customer.update(password=make_password(password))
                customer.update(temp_id='0')
                return redirect('customer:login')
            else:
                return redirect('error:error')
        else:
            return redirect('error:error')
    else:
        return redirect('error:error')


def accoutVarification(request):
    data = getResponses.getResponse(request)
    data['message'] = ""
    if 'id' in request.GET:
        id = request.GET['id']
        if id != '0':
            customer = Customers.objects.filter(temp_id=id)
            if customer:
                customer.update(is_active=True, temp_id='0')
                return redirect('customer:login')
            else:
                return redirect('error:error')
        else:
            return redirect('error:error')
    else:
        return redirect('error:error')


def updatePassword(request):
    data = getResponses.getResponse(request)
    data['message'] = ""
    if 'customer_id' in request.session:
        if request.method == "POST":
            oldPassword = request.POST['oldPassword']
            newPassword = request.POST['newPassword']
            customer = Customers.objects.filter(
                id=request.session['customer_id'])
            if check_password(oldPassword, customer[0].password):
                customer.update(password=make_password(newPassword))
                data['message'] = "password changed successfully"
                return render(request, "customer/updatepassword.html", data)
            else:
                data['message'] = "Old password is not correct"
                return render(request, "customer/updatepassword.html", data)
        else:
            return render(request, "customer/updatepassword.html", data)
    else:
        return redirect("error:error")


def updateProfile(request):
    data = getResponses.getResponse(request)
    data['message'] = ""
    if 'customer_id' in request.session:
        if request.method == "POST":
            street = request.POST['street']
            city = request.POST['city']
            state = request.POST['state']
            country = request.POST['country']
            pincode = request.POST['pincode']
            dob = request.POST['dob']

            address = Address()
            address.customer_id = Customers.objects.filter(
                id=request.session['customer_id'])[0]
            address.street = street
            address.city = city
            address.state = state
            address.country = country

templates/customer/changepassword.html
{% extends '../extends/main.html' %}
{% load static %}
{% block styles %}
<link rel="stylesheet" href="{% static 'css/login.css' %}">
{% endblock styles %}

{% block content %}
<div class="container">
    <div class="row form-container">
        <h3 class="white-text center-align">Change Password</h3>

        {% if message %}
        <div class="col s12 red white-text section" style="margin: 10px;">
            <p>
                {{ message }}
            </p>
        </div>
        {% endif %}

        <form method="post" action="changepassword">
            <div class="input-field col s12">
                <input required id="password" name="password" type="password" />
                <input required name="temp_id" value="{{ temp_id }}" hidden type="text" />
                <label for="password">Enter Your New Password</label>
            </div>
            {% csrf_token %}
            <input required class="btn" type="submit" value="Submit" />
        </form>

        <div class="col s12 m6 center-align">
            <h4><a class="white-text" href="{% url 'customer:signup' %}">Signup</a></h4>
        </div>
        <div class="col s12 m6 center-align">
            <h4><a class="white-text" href="{% url 'customer:forgot' %}">Forgot Password</a></h4>
        </div>
    </div>
</div>


{% endblock content %}

templates/customer/dashboard.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ title }}</title>
</head>
<body>
{{ name }}
{{ email }}
{% for add in address %}
    <li>{{ add.address }}</li>
{% endfor %}
<a href="/customer/logout" >Logout</a><br>
<a href="/cart" >cart</a>
<a href="/customer/updatepassword" >Password change</a>
<a href="/customer/updateprofile" >Profile Update</a>
</body>
</html>

templates/customer/forgotpassword.html
{% extends '../extends/main.html' %}
{% load static %}
{% block styles %}
<link rel="stylesheet" href="{% static 'css/login.css' %}">
<link rel="stylesheet" href="{% static 'css/my-btn.css' %}">
{% endblock styles %}

{% block content %}
<div class="container">
    <div class="row form-container">
        <h3 class="center-align">Forget Password</h3>

        {% if message %}
        <div class="col s12 red white-text section" style="margin: 10px;">
            <p>
                {{ message }}
            </p>
        </div>
        {% endif %}

        <form method="post">
            
            <label >Enter Your Email</label>
            <input required name="email" type="email" id="email" class="my-form"/>
        
            {% csrf_token %}
            <input required class="btn z-depth-0 my-btn" type="submit" value="Submit" />
        </form>

        <div class="col s12 m6 center-align">
            <h4><a class="white-text" href="{% url 'customer:signup' %}">Signup</a></h4>
        </div>
        <div class="col s12 m6 center-align">
            <h4><a class="white-text" href="{% url 'customer:forgot' %}">Login</a></h4>
        </div>
    </div>
</div>


{% endblock content %}

templates/customer/login.html
{% extends '../extends/main.html' %}
{% load static %}
{% block styles %}
<link rel="stylesheet" href="{% static 'css/login.css' %}">
<link rel="stylesheet" href="{% static 'css/topImage.css' %}">
<link rel="stylesheet" href="{% static 'css/my-btn.css' %}">
{% endblock styles %}

{% block content %}
<div class="top-image">
    <div class="second center-align">
        <span>
            Login
        </span>
    </div>
</div>

<div class="row form-container card-panel">
    <div class="col s12 m5">
        <h6 class="heading">New Customer</h6>
        <p>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Inventore molestiae ullam placeat nobis nesciunt quos delectus illo, sequi voluptatibus ut, iste earum excepturi veniam, quis non. Ipsa impedit quam error.
        </p>
        <a class="btn z-depth-0 my-btn" href="{% url 'customer:signup' %}">Signup</a>
            {% comment %} <a href="{% url 'social:begin' 'google-oauth2' %}">Login with Google</a> {% endcomment %}
    </div>

    <div class="col s0 m1"></div>

    <div class="col s12 m5">
            <h6 class="heading">LOGIN FORM</h6>

            <p>If you have an account with us, please login.</p>
            {% if message %}
            <div class="red center-align white-text" style="margin: 10px;border-radius: 4px;">
                <p>
                    {{ message }}
                </p>
            </div>
            {% endif %}
    
            <form method="post">
                <label for="email">Enter Your Email</label>
                <input required class="my-form" name="email" type="email" id="email" />


                <label for="password">Enter Your Password</label>
                <input required class="my-form" name="password" type="password" id="password" />
                {% csrf_token %}
                <input required class="btn z-depth-0 my-btn" type="submit" value="Submit" />
                <a class="btn z-depth-0 my-btn" href="{% url 'customer:forgot' %}">Forgot Password</a>
            </form>
    </div>
</div>


{% endblock content %}

templates/customer/profile.html
{% extends '../extends/main.html' %}
{% load static %}

{% block styles %}
<link rel="stylesheet" href="{% static 'css/topImage.css' %}">
<link rel="stylesheet" href="{% static 'css/my-btn.css' %}">
<link rel="stylesheet" href="{% static 'css/my-card.css' %}">
<link rel="stylesheet" href="{% static 'css/my-link.css' %}">
<link rel="stylesheet" href="{% static 'css/profile.css' %}">
{% endblock styles %}

{% block content %}
<div class="top-image">
    <div class="first center-align">
        <span>
            Your
        </span>
    </div>
    <div class="second center-align">
        <span>
            DashBoard
        </span>
    </div>
</div>

<div class="profile-container">
    <div class="row">
        <div class="col s12 m9">
            <div class="card-panel">
                <h6 class="name">HELLO, {{name}}!</h6>
                <p>This is the place where you can change account info and see what you have bought recently.</p>


                <h6 style="font-weight: 700; border-bottom: 1px solid #dddddd;">RECENT ORDER</h6>

                {%  if orders %}
                <table>
                    <thead>
                    <tr>
                        <th>ORDER #</th>
                        <th>DATE</th>
                        <th>ORDER TOTAL</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for order in orders %}
                        <tr>
                            <td>{{ order.id }}</td>
                            <td>{{ order.order_date }}</td>
                            <td>{{ order.total_price }}</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
                {% endif %}
                <div class="row">
                    
                        <div class="col s12 m6">
                            <h6 class="name" style="margin-top: 50px;">ACCOUNT INFO</h6><hr>
                            <p class="sub-heading">CONTACT INFO</p>
                            <p>{{mobile}}</p>
                            <p>{{email}}</p>

                            <p class="sub-heading">ADDRESS BOOK</p>
                            {% if address %}
                            {% for add in address %}

                            <p class="address-field">{{add.street}}</p>
                            <p class="address-field">{{add.city}}, {{add.state}}</p>
                            <p class="address-field">{{add.country}}, {{add.pincode}}</p>
                            <br>
                            {% endfor %}
                            {% else %}
                            <a class="btn my-btn z-depth-0" href="#">Add a Address</a>
                            {% endif %}
                            
                        </div>

                </div>
            </div>
        </div>

        <div class="col s12 m3">

            <div class="my-card">
                <div class="card-panel contains">

                    <span>Account</span>
                    <p>
                      <ul class="my-link">
                        <li><a href="{% url 'cart:cart' %}">cart</a></li>

                        <li><a href="{% url 'customer:updatepassword' %}">Change Password</a></li>

                        <li><a href="{% url 'customer:updateprofile' %}">Profile Update</a></li>

                        <li><a href="{% url 'blog:addrecipe' %}">Add Recipe to blog</a></li>

                        <li><a href="{% url 'blog:recipe' %}">Blog</a></li>
                      </ul>  
                    </p>
                
                </div>
            </div>

        </div>
    </div>
</div>


{% endblock content%}

templates/customer/signup.html
{% extends '../extends/main.html' %}
{% load static %}
{% block styles %}
<link rel="stylesheet" href="{% static 'css/login.css' %}">
<link rel="stylesheet" href="{% static 'css/topImage.css' %}">
<link rel="stylesheet" href="{% static 'css/my-btn.css' %}">
{% endblock styles %}

{% block content %}
<div class="top-image">
    <div class="first center-align">
        <span>
            Your
        </span>
    </div>
    <div class="second center-align">
        <span>
            Cart
        </span>
    </div>
</div>

<div class="row form-container card-panel">
    <div class="col s12 m5">
        <h6 class="heading">Already a Customer</h6>
        <p>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Inventore molestiae ullam placeat nobis nesciunt quos delectus illo, sequi voluptatibus ut, iste earum excepturi veniam, quis non. Ipsa impedit quam error.
        </p>
        <a class="btn z-depth-0 my-btn" href="{% url 'customer:login' %}">Login</a>
    </div>
    <div class="col s0 m1"></div>

    <div class="col s12 m5">
        <h6 class="heading">SIGNUP FORM</h6>

        <p>Sign Up to create a new account and enjoy our service</p>
    
        {% if message %}
        <div class="red center-align white-text" style="margin: 10px;border-radius: 4px;">
            <p>
                {{ message }}
            </p>
        </div>
        {% endif %}
    
        <form method="post"> {% csrf_token %}
            <label for="name">Enter Your Name</label>
            <input required class="my-form" name="name" type="text" id="name" />
                
            <label for="email">Enter Your Email</label>
            <input required class="my-form" name="email" id="email" type="email" />
    
            <label for="number">Enter Your Number</label>
            <input required class="my-form" name="mobile" type="number" id="number" />
    
            
            <label for="password">Enter Your Password</label>
            <input required class="my-form" name="password" type="password" id="password" />
            
            <input class="btn z-depth-0 my-btn" type="submit" value="Submit" />
        </form>
    </div>
</div>
{% endblock content %}

templates/customer/updatepassword.html
{% extends '../extends/main.html' %}
{% load static %}
{% block styles %}
<link rel="stylesheet" href="{% static 'css/login.css' %}">
<link rel="stylesheet" href="{% static 'css/topImage.css' %}">
<link rel="stylesheet" href="{% static 'css/my-btn.css' %}">
{% endblock styles %}

{% block content %}

<div class="top-image">
    <div class="first center-align">
        <span>
            Update
        </span>
    </div>
    <div class="second center-align">
        <span>
            Password
        </span>
    </div>
</div>

<div class="row form-container card-panel">
    <div class="col s12 m5">
        <h6 class="heading">New Customer</h6>
        <p>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Inventore molestiae ullam placeat nobis nesciunt quos delectus illo, sequi voluptatibus ut, iste earum excepturi veniam, quis non. Ipsa impedit quam error.
        </p>
        <a class="btn z-depth-0 my-btn" href="{% url 'customer:signup' %}">Signup</a>
    </div>

    <div class="col s0 m1"></div>

    <div class="col s12 m5">
            <h6 class="heading">CHANGE PASSWORD</h6>

            <p>You can change your password here</p>
            {% if message %}
            <div class="red center-align white-text" style="margin: 10px;border-radius: 4px;">
                <p>
                    {{ message }}
                </p>
            </div>
            {% endif %}
    
            <form method="post">

                <label for="oldPassword">Enter Your Old Password</label>
                <input required class="my-form" id="oldPassword" name="oldPassword" type="password" />


                <label for="newPassword">Enter New Password</label>
                <input required class="my-form" id="newPassword" name="newPassword" type="password" />
                {% csrf_token %}
                <input class="btn z-depth-0 my-btn" type="submit" value="Change" />                
            </form>
    </div>
</div>

{% endblock content %}

templates/customer/updateprofile.html
{% extends '../extends/main.html' %}
{% load static %}
{% block styles %}
<link rel="stylesheet" href="{% static 'css/login.css' %}">
<link rel="stylesheet" href="{% static 'css/topImage.css' %}">
<link rel="stylesheet" href="{% static 'css/my-btn.css' %}">
{% endblock styles %}

{% block content %}
<div class="top-image">
    <div class="first center-align">
        <span>
            Update
        </span>
    </div>
    <div class="second center-align">
        <span>
            Profile
        </span>
    </div>
</div>

<div class="row form-container card-panel">
    <div class="col s12 m5">
        <h6 class="heading">New Customer</h6>
        <p>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Inventore molestiae ullam placeat nobis nesciunt quos delectus illo, sequi voluptatibus ut, iste earum excepturi veniam, quis non. Ipsa impedit quam error.
        </p>
        <a class="btn z-depth-0 my-btn" href="{% url 'customer:signup' %}">Signup</a>
            {% comment %} <a href="{% url 'social:begin' 'google-oauth2' %}">Login with Google</a> {% endcomment %}
    </div>

    <div class="col s0 m1"></div>

    <div class="col s12 m5">
            <h6 class="heading">LOGIN FORM</h6>

            <p>If you have an account with us, please login.</p>
            {% if message %}
            <div class="red center-align white-text" style="margin: 10px;border-radius: 4px;">
                <p>
                    {{ message }}
                </p>
            </div>
            {% endif %}
    
            <form method="post">
                <label for="street">Enter Your Street Address</label>
                <input required class="my-form" id="street" name="street" type="text" required />
                
                <label for="city">Enter Your City</label>
                <input required class="my-form" id="city" name="city" type="text" required />
                
                <label for="state">Enter Your State</label>
                <input required class="my-form" id="state" name="state" type="text" required />
                
                <label for="country">Enter Your Country</label>
                <input required class="my-form" id="country" name="country" type="text" required />
                
                <label for="pincode">Enter Your Pincode</label>
                <input required class="my-form" id="pincode" name="pincode" type="number" required />
                
                <label for="dob">Enter Your Date Of Birth</label>
                <input required class="my-form" id="dob" name="dob" type="date" required />
                {% csrf_token %}
                <input class="btn z-depth-0 my-btn" type="submit" value="Update" />
            </form>
    </div>
</div>

{% endblock content %}