ChefSolutions/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import homepage, aboutus, search


urlpatterns = [
    path('', homepage, name="index"),
    path('aboutus', aboutus, name="aboutus"),
    path('search', search, name="search"),
    path('auth/', include('social_django.urls', namespace='social')),
    path('customer/', include('customer.urls')),
    path('admin/', admin.site.urls),
    path('error/', include('Error.urls')),
    path('cart/', include('cart.urls')),
    path('products/', include('products.urls')),
    path('placeorder/', include('order.urls')),
    path('blog/', include('blog.urls')),
    path('payment/', include('payment.urls'), name="payment"),
    path('managecs/', include('manageCS.urls'), name="manageCS"),
    path('coupon/', include('coupon.urls'), name="manageCS"),
]

blog/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import addRecipe, recipes, printRecipe, recipesDetail, addComment

app_name = 'blog'

urlpatterns = [
    path('', recipes, name="recipe"),
    path('<int:id>/', recipesDetail, name="recipesDetail"),
    path('add', addRecipe, name="addrecipe"),
    path('print_recipe/<int:rid>', printRecipe, name="printrecipe"),
    path('addComment', addComment, name="addComment"),
]

customer/urls.py
from django.contrib import admin
from django.urls import path, re_path
from django.conf.urls import url
from .views import login, signup, profile, logout, forgotPassword, changePassword, accoutVarification
from .views import updatePassword, updateProfile

app_name = 'customer'

urlpatterns = [
    path('login', login, name="login"),
    path('logout', logout, name="logout"),
    path('signup', signup, name="signup"),
    re_path(r'^forgotpassword', forgotPassword, name="forgot"),
    re_path(r'^verify', accoutVarification, name="varify"),
    path('changepassword', changePassword, name="changepassword"),
    path('updatepassword', updatePassword, name="updatepassword"),
    path('updateprofile', updateProfile, name="updateprofile"),
    path('profile', profile, name="profile"),
]

blog/models.py
from django.db import models
from customer.models import Customers
# Create your models here.


class Recipes(models.Model):
    id = models.IntegerField(primary_key=True)
    customer_id = models.ForeignKey(Customers, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    food_group = models.CharField(max_length=200) # dessert  ,baking

    use_of_products = models.CharField(max_length=1000) #saprated by $
    ingredients = models.TextField(max_length=2000)
#     cooking process
    cooking_process_name = models.CharField(max_length=100)
    cooking_process_method = models.TextField(max_length=2000)

    tags = models.CharField(max_length=100) # all are sparated with a #
    add_date = models.DateTimeField(auto_now=True)
    total_rating = models.IntegerField(default=0)
    total_users = models.IntegerField(default=0)

    is_apporved = models.BooleanField(default=False)
    video_url = models.TextField(default="")

    picture_1 = models.FileField(upload_to='static/blog/recipe' , default='static/blog/recipe/default.png')
    picture_2 = models.FileField(upload_to='static/blog/recipe' , default='static/blog/recipe/default.png')
    picture_3 = models.FileField(upload_to='static/blog/recipe' , default='static/blog/recipe/default.png')

    class Meta:
        db_table = "recipe"

    def tags_as_list(self):
        return self.tags.split(',')


class Comments(models.Model):
    id = models.IntegerField(primary_key=True)
    text = models.TextField()
    recipe = models.ForeignKey(Recipes, on_delete=models.CASCADE)
    user = models.ForeignKey(Customers, on_delete=models.CASCADE)

    class Meta:
        db_table = "comment"

blog/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect, JsonResponse
from .models import Recipes, Comments
from customer.models import Customers
import getResponses
from products.models import Products
from io import BytesIO
from django.http import HttpResponse
from django.template.loader import get_template
from xhtml2pdf import pisa

# Create your views here.

data = {}


def addRecipe(request):

    if 'customer_id' in request.session:
        data = getResponses.getResponse(request)
        if request.method == 'POST':
            recipe = Recipes()
            recipe.customer_id = Customers.objects.filter(
                id=request.session['customer_id'])[0]
            recipe.name = request.POST['name']
            recipe.food_group = request.POST['food_group']
            product_ids = request.POST.getlist('use_of_products')
            recipe.use_of_products = ""
            for id in product_ids:
                recipe.use_of_products += id + "$"
            recipe.ingredients = request.POST['ingredients']
            recipe.cooking_process_name = request.POST['cooking_process_name']
            recipe.cooking_process_method = request.POST['cooking_process_method']
            recipe.tags = request.POST['tags']
            recipe.video_url = request.POST['video_url']

            if 'picture_1' in request.FILES:
                recipe.picture_1 = request.FILES['picture_1']

            if 'picture_2' in request.FILES:
                recipe.picture_2 = request.FILES['picture_2']

            if 'picture_3' in request.FILES:
                recipe.picture_3 = request.FILES['picture_3']

            recipe.save()
            return render(request, 'blog/sentforapporval.html', data)
        else:
            products = Products.objects.all()
            data['products'] = products
            return render(request, 'blog/addrecipe.html', data)
    else:
        return redirect('customer:login')


def recipes(request):
    data = {}
    if 'customer_id' in request.session:
        data = getResponses.getResponse(request)
    data['recipes'] = Recipes.objects.filter(is_apporved=True)

    def ratingSystem(elem):
        return elem.total_rating

    topRecipes = sorted(data['recipes'], key=ratingSystem, reverse=True)

    if len(topRecipes) > 5:
        data['top_rated'] = topRecipes[0:5]
    else:
        data['top_rated'] = topRecipes

    for i in range(0, len(data['recipes'])):
        data['recipes'][i].use_of_products = data['recipes'][i].use_of_products.split('$')[
            :-1]

    return render(request, 'blog/recipes.html', data)


def recipesDetail(request, id):
    data = {}
    if 'customer_id' in request.session:
        data = getResponses.getResponse(request)
    data['recipes'] = Recipes.objects.get(id=id)

    def ratingSystem(elem):
        return elem.total_rating

    topRecipes = sorted(Recipes.objects.filter(
        is_apporved=True), key=ratingSystem, reverse=True)

    if len(topRecipes) > 5:
        data['top_rated'] = topRecipes[0:5]
    else:
        data['top_rated'] = topRecipes

    data['recipes'].use_of_products = data['recipes'].use_of_products.split('$')[
        :-1]

    products = []
    for idx in data['recipes'].use_of_products:
        if idx != '':
            product = Products.objects.filter(id=idx)[0]
            products.insert(0, product)
    data['products'] = products

    data['comments'] = Comments.objects.filter(recipe=data['recipes'])

    return render(request, 'blog/recipesDetail.html', data)


def render_to_pdf(path, params={}):
    template = get_template(path)
    html = template.render(params)
    response = BytesIO()
    pdf = pisa.pisaDocument(BytesIO(html.encode("UTF-8")), response)
    if not pdf.err:
        return HttpResponse(response.getvalue(), content_type='application/pdf')
    else:
        return HttpResponse("Error Rendering PDF", status=400)


def printRecipe(request, rid):
    recipe = Recipes.objects.filter(id=rid, is_apporved=True)
    if recipe.__len__():
        pdf = render_to_pdf('blog/printtemplate.html', {'data': recipe})
        return HttpResponse(pdf, content_type='application/pdf')
    else:
        return redirect('error:error')


def addComment(request):
    if request.method == 'GET':
        return redirect('error:error')

    elif request.method == 'POST':
        customer = Customers.objects.get(id=request.POST['customerId'])
        recipe = Recipes.objects.get(id=request.POST['recipeId'])
        comment = Comments(
            text=request.POST['text'], user=customer, recipe=recipe)
        comment.save()
        return JsonResponse(data={'success': True, 'comment': comment.text})

templates/blog/addrecipe.html
{% extends "../extends/main.html" %}
{% load static %}
{% block styles %}
<link rel="stylesheet" href="{% static 'css/login.css' %}">
<link rel="stylesheet" href="{% static 'css/topImage.css' %}">
<link rel="stylesheet" href="{% static 'css/my-btn.css' %}">
<style>
    .my-form{
        display: block;
        width: 100%;
    }

    .my-label{
        position: static !important;
    }

    .select-dropdown{
        border: 1px solid grey !important;
    }
</style>
{% endblock styles %}

{% block content %}
<div class="top-image">
    <div class="first center-align">
        <span>
            Write
        </span>
    </div>
    <div class="second center-align">
        <span>
            Blog
        </span>
    </div>
</div>

<div class="row form-container card-panel">
    <div class="col s12 m5">
        <h6 class="heading">New Customer</h6>
        <p>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Inventore molestiae ullam placeat nobis nesciunt quos delectus illo, sequi voluptatibus ut, iste earum excepturi veniam, quis non. Ipsa impedit quam error.
        </p>
        <a class="btn z-depth-0 my-btn" href="{% url 'customer:signup' %}">Signup</a>
    </div>

    <div class="col s0 m1"></div>

    <div class="col s12 m5">
            <h6 class="heading">Write A Blog</h6>

            <p>Hey {{ Customer.name }}, here You can write a blog for our product</p>

            {% if message %}
            <div class="red center-align white-text" style="margin: 10px;border-radius: 4px;">
                <p>
                    {{ message }}
                </p>
            </div>
            {% endif %}
    
            <form method="post" enctype="multipart/form-data" >{% csrf_token %}
                <label>Name</label>
                <input class="my-form browser-default" name="name" required type="text" />

                <label>Food Group</label>
                <input class="my-form browser-default" name="food_group" required type="text" />

{#                <label>Name</label>#}
{#                <input class="my-form browser-default" name="no_of_portions" required type="number" />#}

                    <label>Our Product Used</label>
                    <select multiple name="use_of_products">
                        {%  for product in products %}
                            <option value="{{ product.id }}">{{ product.name }}</option>
                        {% endfor %}
                    </select>

{#                <input class="my-form browser-default" name="use_of_products" required type="text" />#}

                <label class="my-label">Ingredients</label>
                <input class="my-form browser-default" name="ingredients" required type="text" />

                <label>Cooking Process Name</label>
                <input class="my-form browser-default" name="cooking_process_name" required type="text" />

                <label>Cooking Process Method</label>
                <textarea class="my-form browser-default" name="cooking_process_method"  ></textarea>

                <label>Tags ( saprated with  a comma (','))</label>

                <input class="my-form browser-default custom-class" name="tags" required type="text" />

                <label>Youtube Video Url</label>
                <input class="my-form browser-default" name="video_url" required type="text" />


                <label>Picture 1</label>
                <input name="picture_1" required type="file" style="display: block;margin-bottom: 20px;"/>


                <label>Picture 2</label>
                <input name="picture_2" required type="file" style="display: block;margin-bottom: 20px;"/>

                <label>Picture 3</label>
                <input name="picture_3" required type="file" style="display: block;margin-bottom: 20px;"/>
                <br>
                <input class="btn my-btn z-depth-0" name="submit" required type="submit" value="Submit" />
            </form>
    </div>
</div>


{% endblock content %}



{% comment %} 
{{ customer.name }}
{{ customer.email }}
<img height="100" width="100" src="/{{ customer.profile_pic }}">
 {% endcomment %}
{% block scripts %}
<script required type="text/javascript">
    $(document).ready(function(){
        $('select').formSelect();
    });
</script>
{% endblock scripts %}

templates/blog/printtemplate.html
<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <title>Sales Report</title>
    <style type="text/css">
        @page {
            size: A4;
            margin: 1cm;
        }
        .table {
            width: 100%;
            max-width: 100%;
            margin-bottom: 5px;
            background-color: #fff;
        }
        .table th,
        .table td {
            padding: 5px;
            vertical-align: top;

            text-align: center;
        }
        .footer-tab td {
            text-align: center;
        }
        .table {
            border : 1px solid #000;

        }


        .table .table {
            background-color: #fff;

        }
        .list-group {
            display: block;
            width: 100%;
            list-style: none;
            margin-top: 15px;
            margin-bottom: 15px;
        }
        .list-group p {
            width: 100%;
            height: 20px;
            line-height: 20px;
            list-style: none;
            font-size: 1.1em;
        }
    </style>
</head>
<body>

<div class="container">



        <div class="card-header">


        </div>
        <table class="top-table">
            <tbody>
                <tr>
                    <td colspan="2"><h3>Recipe No : CAS100</h3><h2>Teriyaki Glazed Tofu with Stir Fried Asian Greens</h2></td>
                    <td align="right"><img src="static/images/logocf.png" width="70" height="70"></td>
                    <td align="right"><img src="static/images/office.jpg" width="150" height="100"></td>
                </tr>

            </tbody>
        </table>
    <br>

        <table class="table">
            <tbody>
                <tr>
                    <td>Chef Solutions Ingredients used</td>
                    <td>Steps Involved in Cooking:</td>
                </tr>
            </tbody>
        </table>
        <h3>Extras</h3>
         <table class="table" >
            <tbody>
                <tr>
                    <td>Chef Solutions Ingredients used</td>

                </tr>
            </tbody>
        </table>
         <h3>Similar</h3>
         <table class="table" >
            <tbody>
                <tr>
                    <td>More similar recipes which can be made by using CS ingredients</td>

                </tr>
            </tbody>
        </table>
        <br>
        <table class="footer-tab" >
            <tbody>
                <tr>
                    <td >For any feedback Contact our customer care executive at<br>
                    Tel: +91 22 4023 0273 or +91 80494 40899 | Email: care@namosri.com<br>
                    Join our community for Food Service experts for more recipe ideas and information exchange:<br>
                    www.chef-solutions.com| www.facebook.com/chefsolutions| www.namosri.com</td>
                </tr>
                <tr>
                    <td style="background-color: #f4b400; height: 20px;"></td>
                </tr>
            </tbody>
        </table>
</div>

</body>
</html>

templates/blog/recipes.html
{% extends "../extends/main.html" %}
{% load static %}

{% block styles %}
<link rel="stylesheet" href="{% static 'css/topImage.css' %}">
<link rel="stylesheet" href="{% static 'css/my-btn.css' %}">
<link rel="stylesheet" href="{% static 'css/my-card.css' %}">
<style>
    .flow-text{
        margin: 0 !important;
    }
</style>
{% endblock styles %}

{% block content %}

<div class="top-image">
    <div class="first center-align">
        <span>
            Read
        </span>
    </div>
    <div class="second center-align">
        <span>
            Blog
        </span>
    </div>
</div>

{% if recipes %}

<div class="blog-container" style="margin: 10px;">
    <div class="row">
        <div class="col s12 m4">
            
            <div class="card-panel center-align">
        
                <h5>Most Rated Recipes</h5>
                <p>
                    {% for recipe in top_rated %}
                    <h6 class="center-align" style="text-transform: uppercase;">{{ recipe.name }}</h6>
                    <a href="{% url 'blog:recipesDetail' recipe.id %}">
                        <img src="/{{recipe.picture_1  }}" style="max-width: 200px;"/>
                    </a>
                    <br>
                    <hr>
                    {% endfor %}
                </p>
            </div>
        
        </div>
        <div class="col s12 m8">
            <div class="my-card">
                <div class="card-panel contains">
            
                    <span>Blog</span>
                    <p>
                        {% for recipe in recipes %}
                        <h4 class="left" style="text-transform: uppercase;">{{ recipe.name }}</h4>
                        <h5 class="right" style="border: 1px solid grey; padding: 5px;">{{ recipe.add_date }}</h5>
                        <div class="center-align">

                            <iframe style="width: 100%;" height="400" src="{{ recipe.video_url }}" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe st>

{#                            <div class="carousel carousel-slider">#}
{#                                <a class="carousel-item" href="#one!">#}
{#                                    <img src="/{{recipe.picture_1  }}" style="max-height: 300px;" />#}
{#                                </a>#}
{#                                <a class="carousel-item" href="#two!">#}
{#                                    <img src="/{{recipe.picture_2  }}" style="max-height: 300px;"/>#}
{#                                </a>#}
{#                                <a class="carousel-item" href="#three!">#}
{#                                    <img src="/{{recipe.picture_3  }}" style="max-height: 300px;" />#}
{#                                </a>                 #}
{#                            </div>#}
                        </div>
                        
                        <p class="left-align" style="margin-top: 30px !important;">
                            Submitted-By: {{ recipe.customer_id.name }}
                        </p>
        
                        <div class="row center-align">

                                <div class="col m3"></div>
                                <div class="col m2"><img class="materialboxed" src="/{{recipe.picture_1  }}" style="width: 100px;"/></div>
                                <div class="col m2"><img class="materialboxed" src="/{{recipe.picture_2  }}" style="width: 100px;"/></div>
                                <div class="col m2"><img class="materialboxed" src="/{{recipe.picture_3  }}" style="width: 100px;"/></div>
                        </div>

{#                        {% for pro in recipe.use_of_products %}#}
{#                        <div class="chip">#}
{#                            {{ pro }}#}
{#                        </div>#}
{#                        {% endfor %}#}

                        <br>

                        <a href="{% url 'blog:recipesDetail' recipe.id %}" class="btn z-depth-0 my-btn" style="margin-top: 30px;margin-bottom: 50px;" type="button">Read More</a>
        
                        <hr>
                        
                        {% endfor %}
                
                    </p>
                </div>
            </div>
        </div>
    </div>
</div>

{% else %}
<h3 class="center-align">Nothing wrote yet. Be the first one to write</h3>
{% endif %}

{% endblock content %}

{% block scripts %}
<script>
	 $(document).ready(function(){
	     $('.carousel.carousel-slider').carousel({
		    fullWidth: true,
		    indicators: true
		  });
      
	  });
    // $('.carousel.carousel-slider').carousel({
    //     fullWidth: true
    // });
</script>
{% endblock scripts %}

templates/blog/recipesDetail.html
{% extends "../extends/main.html" %}
{% load static %}

{% block styles %}
<link rel="stylesheet" href="{% static 'css/topImage.css' %}">
<link rel="stylesheet" href="{% static 'css/my-btn.css' %}">
<link rel="stylesheet" href="{% static 'css/my-card.css' %}">
<style>
    .flow-text{
        margin: 0 !important;
    }
</style>
{% endblock styles %}

{% block content %}

<div class="top-image">
    <div class="first center-align">
        <span>
            Read
        </span>
    </div>
    <div class="second center-align">
        <span>
            Blog
        </span>
    </div>
</div>

{% if recipes %}

<div class="blog-container" style="margin: 10px;">
    <div class="row">
        <div class="col s12 m4">
            <div class="card-panel">
                <div class="card-panel center-align">
    
                    <h5>Most Rated Recipes</h5>
                    <p >
                        {% for recipe in top_rated %}
                        <h6 class="center-align" style="text-transform: uppercase;">{{ recipe.name }}</h6>
                        <a href="{% url 'blog:recipesDetail' recipe.id %}" >
                            <img src="/{{recipe.picture_1  }}" class="center-align" style="max-width: 200px;"/>
                        </a>
                        <br>
                        <hr>
                        {% endfor %}
                    </p>
                </div>
            </div>
        </div>
        <div class="col s12 m8">
            <div class="my-card">
                <div class="card-panel contains">
            
                    <span>Blog</span>
                    <p>
                        
                        <h4 class="left" style="text-transform: uppercase;">{{ recipes.name }}</h4>
                        <h5 class="right" style="border: 1px solid grey; padding: 5px;">{{ recipes.add_date }}</h5>
                        <div class="center-align">
                            <iframe style="width: 100%;" height="400" src="{{ recipes.video_url }}" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe st>
                        </div><br>
                        <p class="flow-text">
                            Images:
                        </p>
                        <div class="center-align">
                            <div class="row">
                                <div class="col"><img class="materialboxed" src="/{{recipes.picture_1  }}" style="width: 200px;"/></div>
                                <div class="col"><img class="materialboxed" src="/{{recipes.picture_2  }}" style="width: 200px;"/></div>
                                <div class="col"><img class="materialboxed" src="/{{recipes.picture_3  }}" style="width: 200px;"/></div>
                            </div>



{#                            <div class="carousel carousel-slider">#}
{#                                <a class="carousel-item" href="#one!">#}
{#                                    <img src="/{{recipes.picture_1  }}" style="width: 100%; height: 100%;"/>#}
{#                                </a>#}
{#                                <a class="carousel-item" href="#two!">#}
{#                                    <img src="/{{recipes.picture_2  }}" style="width: 100%; height: 100%;"/>#}
{#                                </a>#}
{#                                <a class="carousel-item" href="#three!">#}
{#                                    <img src="/{{recipes.picture_3  }}" style="width: 100%; height: 100%;" />#}
{#                                </a>                 #}
{#                            </div>#}
                        </div>
                        
                        <p class="left-align" style="margin-top: 30px !important;">
                            Added-By: <b>{{ recipes.customer_id.name }}</b>
                        </p>
                        <p class="flow-text">
                            <small>Food Group: {{ recipes.food_group }}</small>
                        </p>
                        {% for tag in recipes.tags_as_list %}
                            <div class="chip">
                            {{ tag }}
                            </div>
                        {% endfor %}
                        <p class="flow-text">
                            Our Products Used:
                        </p>

                        {% if products %}
                        <table>
                            <thead>
                                <tr>
                                    <th></th>
{#                                    <th>Product Id</th>#}
{#                                    <th>Product Name</th>#}
                                    <th></th>

                                </tr>
                            </thead>
                            <tbody>
                                {% for product in products %}
                                    <tr>
                                        <td><img src="/{{ product.picture_1 }}" style="height: 50px; width: 50px;"></td>
{#                                        <td>{{ product.id }}</td>#}
                                        <td>{{ product.name }}</td>
                                        <td class="right-align"><a class="my-btn btn z-depth-0" href="/products/details/{{ product.id }}">Open</a></td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table><br>
                        {% endif %}
                        <p class="flow-text">
                            Ingredients:
                            <small>{{ recipes.ingredients }}</small>
                        </p>
                        <p class="flow-text">
                            Cooking Process Name:<br>
                            <small>{{ recipes.cooking_process_name }}</small>
                        </p>
                        <p class="flow-text">
                            Cooking Process:<br>
                            <small>{{ recipes.cooking_process_method }}</small>
                        </p>

                    </p>

                    <h4 class="left-align" style="margin-bottom: 40px;">Comments</h4>
                    
                    {% if comments %}
                    <ul class="collection">
                        {% for comment in comments %}
                        <li class="collection-item avatar">
                            <img src="/{{ comment.user.profile_pic }}" alt="" class="circle">
                            <h4 class="title teal-text" style="margin-top: 0px;">{{ comment.user.name }}</h4>
                            <p>{{ comment.text }}</p>
                        </li>
                        {% endfor %}
                    </ul>
                    {% else %}
                    <h6 class="left-align">No Comments Yet. Be The First One To Add</h6>
                    {% endif %}

                    {% if customer %}
                    <h5 class="left-align" style="margin-top: 40px; margin-bottom: 40px;">Add Comment</h5>

                    <form id="commentForm">
                        {% csrf_token %}
                        <p id="customerId" class="hide">{{ customer.id }}</p>
                        <p id="recipeId" class="hide">{{ recipes.id }}</p>
                        <p id="customerName" class="hide">{{ customer.name }}</p>
                        <p id="customerImage" class="hide">{{ customer.profile_pic }}</p>
                        <textarea class="materialize-textarea" name="comment" style="border: 1px solid grey; padding: 20px;" placeholder="Write Your Comment" required></textarea>
                        <input required class="my-btn btn z-depth-0" type="submit" value="Add Comment">
                    </form>
                    {% else %}
                    <h6 class="center-align">Login to add comments</h6>
                    {% endif %}
                    
                </div>
                
            </div>
        </div>
    </div>
</div>

<div id="modal1" class="modal">
    <div class="modal-content">
        <h4>Error While Commenting</h4>
        <p>Some Error Occured While Commenting Try Again After Reloading The Page</p>
    </div>
</div>

{% else %}
<h3 class="center-align">No Such Recipe</h3>
{% endif %}

{% endblock content %}

{% block scripts %}
<script>
    $('document').ready(function(){
        $('.carousel.carousel-slider').carousel({
            fullWidth: true
        });
        $('.modal').modal();

        $('.materialboxed').materialbox();

    })
</script>
<script src="{% static 'js/comment.js' %}"></script>
{% endblock scripts %}                

templates/blog/sentforapporval.html
{% extends "../extends/main.html" %}
{% load static %}

{% block styles %}
<link rel="stylesheet" href="{% static 'css/topImage.css' %}">
{% endblock styles %}   

{% block content %}
<div class="top-image">
    <div class="second center-align">
        <span>
            Sent
        </span>
    </div>
</div>

<h4 class="center-align">Sent For Approval</h4>
{% endblock content %} 